---
- name: "Play for configuring a docker host"
  hosts: docker
  become: true
  tasks:
    - name: Install docker
      ansible.builtin.import_tasks: roles/common/tasks/install_docker.yaml

    - name: Install portainer via docker
      ansible.builtin.import_tasks: roles/common/tasks/install_portainer.yaml
